
- name: Install barebones Routinator3000
  gather_facts: true
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Install symlink to python 3.6 if it doesn't exist
      file:
        dest: '/usr/bin/python'
        state: absent
        owner: root
        group: root

    - name: Instalar paquetes genéricos
      apt:
         pkg:
            - htop
            - tmux
            - rsync
            - build-essential
            - doxygen
            - cmake
         state: present	     
         update_cache: yes

    - name: Add user r3k
      user:
        name: r3k
        state: present
        shell: /bin/bash
        groups: 
           - sudo
           
    - name: Create directories for r3k 
      file:
        dest: "{{ item }}"
        state: directory
        owner: r3k
        group: r3k
      with_items:
         - /home/r3k/log
         - /home/r3k/export

    - name: Instalar RUST via rustup
      become_user: r3k
      shell: |
         cd /home/r3k
         curl https://sh.rustup.rs -sSf > rustup.sh
         sh rustup.sh -y 
         rm rustup.sh
        
    - name: Instalar ROUTINATOR 3000
      become_user: r3k
      shell: |
         cd /home/r3k
         source /home/r3k/.cargo/env
         /home/r3k/.cargo/bin/cargo install routinator

    - name: Inicializar y ejecutar ROUTINATOR 3000
      become_user: r3k
      shell: |
         /home/r3k/.cargo/bin/routinator init --accept-arin-rpa

    - name: Instalar la RTRlib y el RTRClient
      become_user: root
      shell: |
         git clone https://github.com/rtrlib/rtrlib.git rtrlib.git
         cd rtrlib.git
         cmake -D CMAKE_BUILD_TYPE=Release -D RTRLIB_TRANSPORT_SSH=No .
         make
         make install
         echo /usr/local/lib >> /etc/ld.so.conf.d/usr.local.lib.conf
         ldconfig
         